ALTER TABLE eval_eleve DISABLE KEYS;
DELETE FROM eval_eleve;
ALTER TABLE eval_eleve ENABLE KEYS;

ALTER TABLE eval DISABLE KEYS;
DELETE FROM eval;
ALTER TABLE eval ENABLE KEYS;

ALTER TABLE eleve_module DISABLE KEYS;
DELETE FROM eleve_module;
ALTER TABLE eleve_module ENABLE KEYS;

ALTER TABLE eleve DISABLE KEYS;
DELETE FROM eleve;
ALTER TABLE eleve ENABLE KEYS;

ALTER TABLE matiere DISABLE KEYS;
DELETE FROM matiere;
ALTER TABLE matiere ENABLE KEYS;

ALTER TABLE module DISABLE KEYS;
DELETE FROM module;
ALTER TABLE module ENABLE KEYS;